package step.spline;

public enum SurfaceForm {
    PLANE_SURF,
    CYLINDRICAL_SURF,
    CONICAL_SURF,
    SPHERICAL_SURF,
    TOROIDAL_SURF,
    SURF_OF_REVOLUTION,
    RULED_SURF,
    GENERALISED_CONE,
    QUADRIC_SURF,
    SURF_OF_LINEAR_EXTRUSION,
    UNSPECIFIED
}
